### ISSUE TITLE
help extarcting info

### ISSUE THREAD

**Issue by vzlgdu** [mperlet/fritzl#5]
Hi, I need to use info like temperature or power usage outside your example.

Please, can you help me to assign all info extracted from PyDect200 to some variables tha can be used outside the cycle "or dev_id in info.keys():"?

I'm trying to assign it to a variable but I catch always "syntax error"...

Thanks

**Comment by mperlet** [comment]
Hey try this snippet. You get a list of dictionarys. Every dict holds the information about one socket.
```
api = PyDect200.PyDect200("myVeryVeryStrongPassword")
socket_information = [
{
"id": id,
"temperature": api.get_temperature_single(id),
"name": api.get_device_name(id), 
"energy": api.get_energy_single(id), 
"power": api.get_power_single(id), 
"state": api.get_state(id) == "1"
} for id in api.get_device_ids()
]
```

This produces the following output:
```
In [57]: socket_information = [
   ....: {
   ....: "id": id,
   ....: "temperature": api.get_temperature_single(id),
   ....: "name": api.get_device_name(id), 
   ....: "energy": api.get_energy_single(id), 
   ....: "power": api.get_power_single(id), 
   ....: "state": api.get_state(id) == "1"
   ....: } for id in api.get_device_ids()
   ....: ]

In [58]: socket_information
Out[58]: 
[{'energy': u'337',
  'id': u'087610094277',
  'name': u'Weihnachtsbraum',
  'power': u'2360',
  'state': True,
  'temperature': 22.5},
 {'energy': u'6368',
  'id': u'087610097318',
  'name': u'Tansu',
  'power': u'0',
  'state': False,
  'temperature': 18.5}]

```

With `socket_information[0]["temperature"]` you get the temperature of the first socket.
**Warning: This method is not efficient and produces many api calls.**
