### ISSUE TITLE
PyDect200 seems to be broken with Fritz OS7

### ISSUE THREAD

**Issue by thomas-villagers** [mperlet/fritzl#6]
Hi! 

On my recently updated fritz box devices are not found:

```
f = PyDect200('password')
f.get_device_names()

```
Expected result: devices dict.
Actual Result: 

`{u'inval':u'inval'}
`

**Comment by mperlet** [comment]
hi thomas-villagers,
which fritzbox and which version (7.00/7.01) exactly do you use? And which devices have you connected or do you expect from the response?

**Comment by thomas-villagers** [comment]
Hi mperlet.
Thank you for the quick reply. 
I have one FRITZ!DECT 200 wall plug switch and Fritz!OS 07.01 on a 7490. 

- thomas

**Comment by mperlet** [comment]
I can only reproduce the error if I use the wrong password. The error handling is not good at this point yet.

```
In [1]: from PyDect200 import PyDect200
In [2]: f = PyDect200("correct_password")
In [3]: f.get_device_names()
Out[3]: 
{u'0876xxx': u'Steckdose 1',
 u'0875xxx': u'Steckdose 2'}

In [4]: f.sid
Out[4]: u'27bbc6f485e6e123'

In [5]: f2 = PyDect200("wrong_password")
In [6]: f2.get_device_names()
Out[6]: {u'inval': u'inval'}

In [7]: f2.sid
Out[7]: u'0000000000000000'
```
Have you possibly created a user with a username for the login? This is actually not implemented yet. I'll add that later.

**Comment by thomas-villagers** [comment]
yes, I think that's the point. I HAD to add a user with username a while ago for NAS related stuff. 
Odd, before the upgrade to 7.01 your script worked fine.

**Comment by mperlet** [comment]
Hey @thomas-villagers,
i added a username argument with PR: https://github.com/mperlet/PyDect200/pull/7.
So after a `pip install --upgrade PyDect200` you shoud get version 0.0.16.
You can use 
```
f = PyDect200('password', username='fritzbox-user')
```
to create instance. 
I also added a `login_ok()` method to check a valid fritzbox session id. Hopefully it'll help you.

**Comment by thomas-villagers** [comment]
great & works, thank you!
